// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbgzjvxgkslgkcppsmcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiZ3pqdnhna3NsZ2tjcHBzbWNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNzgxNTAsImV4cCI6MjA2Nzg1NDE1MH0.OQU6vB0Wzzt00AnioEugnOx5TJk_6V7ngWRZ19_cQ1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});